-- MySQL Script generated by MySQL Workbench
-- Sun Nov 29 12:28:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_puzzleservices
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_puzzleservices
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_puzzleservices` ;
USE `db_puzzleservices` ;

-- -----------------------------------------------------
-- Table `db_puzzleservices`.`tb_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_puzzleservices`.`tb_users` (
  `idUser` INT(9) NULL DEFAULT NULL AUTO_INCREMENT,
  `cpfUser` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `celular` VARCHAR(14) NOT NULL,
  `dataNasc` DATE NOT NULL,
  `logradouro` VARCHAR(80) NOT NULL,
  `numero` CHAR(5) NOT NULL,
  `complemento` VARCHAR(30) NULL DEFAULT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(40) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `cep` CHAR(9) NOT NULL,
  `avaliacao` FLOAT NULL DEFAULT NULL,
  `senha` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idUser`));


-- -----------------------------------------------------
-- Table `db_puzzleservices`.`tb_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_puzzleservices`.`tb_categories` (
  `idCategory` INT(9) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL UNIQUE,
  PRIMARY KEY (`idCategory`));


-- -----------------------------------------------------
-- Table `db_puzzleservices`.`tb_providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_puzzleservices`.`tb_providers` (
  `idProvider` INT(9) NULL DEFAULT NULL AUTO_INCREMENT,
  `cpfProvider` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `celular` VARCHAR(14) NOT NULL,
  `dataNasc` DATE NOT NULL,
  `logradouro` VARCHAR(80) NOT NULL,
  `numero` CHAR(5) NOT NULL,
  `complemento` VARCHAR(30) NULL DEFAULT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(40) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `cep` CHAR(9) NOT NULL,
  `avaliacao` FLOAT NULL DEFAULT NULL,
  `senha` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idProvider`));


-- -----------------------------------------------------
-- Table `db_puzzleservices`.`tb_categories_providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_puzzleservices`.`tb_categories_providers` (
  `idCategory` INT(9) NOT NULL,
  `idProvider` INT(9) NOT NULL,
  PRIMARY KEY (`idCategory`, `idProvider`),
  INDEX `fk_categories_providers_idCategory` (`idCategory` ASC),
  INDEX `fk_categories_providers_idProvider` (`idProvider` ASC),
  CONSTRAINT `fk_categories_providers_idCategory`
    FOREIGN KEY (`idCategory`)
    REFERENCES `db_puzzleservices`.`tb_categories` (`idCategory`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categories_providers_idProvider`
    FOREIGN KEY (`idProvider`)
    REFERENCES `db_puzzleservices`.`tb_providers` (`idProvider`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `db_puzzleservices`.`tb_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_puzzleservices`.`tb_services` (
  `idService` INT(9) NULL DEFAULT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(120) NOT NULL,
  `localizacao` VARCHAR(150) NOT NULL,
  `dataPublic` DATETIME NOT NULL,
  `idUser` INT(9) NOT NULL,
  PRIMARY KEY (`idService`),
  INDEX `fk_idUser` (`idUser` ASC),
  CONSTRAINT `fk_idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `db_puzzleservices`.`tb_users` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `db_puzzleservices`.`tb_budgets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_puzzleservices`.`tb_budgets` (
  `idBudget` INT(9) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(120) NOT NULL,
  `dataFinal` DATE NULL DEFAULT NULL,
  `idService` INT(9) NOT NULL,
  `idProvider` INT(9) NOT NULL,
  PRIMARY KEY (`idBudget`),
  INDEX `fk_idService` (`idService` ASC),
  INDEX `fk_idProvider` (`idProvider` ASC),
  CONSTRAINT `fk_idService`
    FOREIGN KEY (`idService`)
    REFERENCES `db_puzzleservices`.`tb_services` (`idService`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idProvider`
    FOREIGN KEY (`idProvider`)
    REFERENCES `db_puzzleservices`.`tb_providers` (`idProvider`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `db_puzzleservices`.`tb_categories_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_puzzleservices`.`tb_categories_services` (
  `idService` INT(9) NOT NULL,
  `idCategory` INT(9) NOT NULL,
  PRIMARY KEY (`idService`,`idCategory`),
  INDEX `fk_categories_services_idService` (`idService` ASC),
  INDEX `fk_categories_services_idCategory` (`idCategory` ASC),
  CONSTRAINT `fk_categories_services_idService`
    FOREIGN KEY (`idService`)
    REFERENCES `db_puzzleservices`.`tb_services` (`idService`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categories_services_idCategory`
    FOREIGN KEY (`idCategory`)
    REFERENCES `db_puzzleservices`.`tb_categories` (`idCategory`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
